run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - stylecheck
    - unused

linters-settings:
  stylecheck:
    checks:
      - ST1003
